import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";

// Use Inter for the main font
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-geist-sans", // Keeping this name so globals.css works
});

// Use Roboto Mono for the code/mono font
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono", // Keeping this name so globals.css works
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}